config/routes.rb
Rails.application.routes.draw do



  devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin,  skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

scope module: :public do
  root :to => "homes#top"
  resources :posts,  only: [:index, :new, :show, :edit, :update, :create, :destroy] do
    resources :post_comments, only: [:new, :create, :destroy]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  get '/post/hashtag/:name' => 'posts#hashtag'
  get '/post/hashtag' => 'posts#hashtag'

  get "users/quit" => "users#quit"
  patch "users/withdraw" => "users#withdraw"
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
    member do
      get :favorites
    end
    collection do
    get 'search'
    end
  end
  resources :chats, only: [:show, :create]
  resources :rooms, only: [:index]
  resources :notifications, only: [:index]
end

  namespace :admin do
    get "/" => "homes#top"
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :hashtag_posts, dependent: :destroy
  has_many :hashtags, through: :hashtag_posts
  has_many :notifications, dependent: :destroy


  validates :body, length:{maximum:200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  after_create do
      post = Post.find_by(id: id)
      hashtags = hashbody.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
      hashtags.uniq.map do |hashtag|
        tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
        post.hashtags << tag
    end
  end

  before_update do
      post = Post.find_by(id: id)
      post.hashtags.clear
      hashtags = hashbody.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
      hashtags.uniq.map do |hashtag|
        tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
        post.hashtags << tag
      end
  end
  
  #いいね通知
  def create_notification_favorite!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user_id, id, 'favorite'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'favorite'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  #コメント通知
  def create_notification_post_comment!(current_user, post_comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = PostComment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_post_comment!(current_user, post_comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_post_comment!(current_user, post_comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_post_comment!(current_user, post_comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: 'post_comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end


end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<div class="col-md-8">
<% @posts.order(created_at: :desc).each do |post| %>
  <div class="border mt-2", style="border-radius: 30px;">
    <div class="mt-1 ml-2">
    <%= image_tag post.user.get_profile_image, style: "border-radius: 50%; width: 50px; height: 50px;" %>
    <strong><%= post.user.name %></strong>
      <span style="float: right;", class="mr-md-3 mr-2">
      <%= link_to admin_post_path(post.id), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger" do %>
        <i class="fas fa-trash-alt"></i>
      <% end %>
      </span>
      <span class="mr-md-2 mr-2" style="float: right; font-size: 13px;" data-livestamp="<%=post.created_at%>"></span>
    </div>
    <div class="ml-md-2 mr-md-2">
      <p><%= post.body %></p>
      <p><%= render_with_hashtags(post.hashbody) %>
      <p>場所 : <%= post.user.prefecture.name %></p>
      <table class="ml-md-2" width="150">
        <tbody>
          <tr>
            <td id="favorite_buttons_<%= post.id %>"><%= render "public/favorites/favorite", post: post %></td>
            <td><%= link_to post_path(post.id), style: "color: black;" do %>
                  <i class="far fa-comment"></i> <%= post.post_comments.count %>
                <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
<% end %>
</div>