config/routes.rb
Rails.application.routes.draw do



  devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin,  skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

scope module: :public do
  root :to => "homes#top"
  resources :posts,  only: [:index, :new, :show, :edit, :update, :create, :destroy] do
    resources :post_comments, only: [:new, :create, :destroy]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  get '/post/hashtag/:name' => 'posts#hashtag'
  get '/post/hashtag' => 'posts#hashtag'

  get "users/quit" => "users#quit"
  patch "users/withdraw" => "users#withdraw"
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
    member do
      get :favorites
    end
    collection do
    get 'search'
    end
  end
  resources :chats, only: [:show, :create]
  resources :rooms, only: [:index]
  resources :notifications, only: [:index]
end

  namespace :admin do
    get "/" => "homes#top"
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :user_rooms
  has_many :rooms, through: :user_rooms
  has_many :chats


  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # 自分方の通知
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  # 相手からの通知
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true
  validates :profile, length: {maximum: 200}
  validates :birth_year, length: { is: 4 }
  validates :birth_month, length: { is: 2 }
  validates :birth_day, length: { is: 2 }
  validates :user_status, presence: true

  enum user_status: { "有効": 0, "自己退会": 1, "強制退会": 2, "ゲストログイン": 3 }

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.jp', prefecture_code: "13", birth_year: '1996', birth_month: '03', birth_day: '21') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def active_for_authentication?
    self.user_status == "有効" || self.user_status == "ゲストログイン"
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  include JpPrefecture
    jp_prefecture :prefecture_code

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  def index 
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end 
  
  def edit
    @user = User.find(params[:id])
  end 
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:user_status)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<h2>プロフィールの編集</h2>
<div class="col-md-8">
  <%= form_with model: @user, url: admin_user_path(@user), local:true do |f| %>
      <%= render 'layouts/errors', model: @user %>
      
      <div class="form-group">
        <%= f.label :name, "ユーザーネーム" %>
        <%= f.text_field :name, class: "form-control col-md-4" %>
      </div>
      <div class="form-group">
        <%= f.label :profile_image, "プロフィール画像" %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
       </div>
       
       <div class="form-group">
        <%= f.label :profile, "プロフィール" %>
        <%= f.text_area :profile, class: "form-control introduction" %>
       </div>
       
       <div class="form-group">
          <%= f.label :ユーザーステータス, class: "col-sm-4" %>
        <div class="form-check">
          <%= f.select :user_status, User.user_statuses.keys %>
        </div>
       </div>
       <div class="form-group">
        <%= f.submit "編集内容を保存", class: 'btn btn-secondary' %>
        </div>
  <% end %>
</div>

app/views/admin/users/index.html.erb
<div class='container px-5 px-sm-0 ml-md-3'>
  <div class='row'>
    <div class='col-12 px-0 mx-auto mt-3'>
      <h2>会員一覧</h2>
    </div>

      <table class='table table-hover shadow-lg mt-3'>
        <thead class="bg-light">
          <tr>
            <th>ユーザーID</th>
            <th><u>ユーザー名</u></th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody class="border-bottom">
          <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><u><%= link_to user.name ,admin_user_path(user)%></u></td>
              <td><%= user.email %></td>
              <td><%= user.user_status %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="col-md-8 border border-light shadow">
  <div class="row border-bottom border-primary">
    <div class="col-md-3"><%= image_tag @user.get_profile_image, style: "border-radius: 50%; width: 150px; height: 150px;" %></div>
    <div class="col-md-5 offset-md-3 ">
      <div class="text-right">
      <%= link_to edit_admin_user_path(@user), class: "text-dark" do %>
      <i class="fas fa-edit"></i>
      <% end %>
      </div>
      <div class="text-center"><%= @user.id %></div>
      <div class="text-center"><%= @user.name %></div>
      <div class="text-center"><%= @user.email %></div>
      <div class="text-center"><%= @user.prefecture.name %></div>
      <div class="text-center"><i class="fas fa-birthday-cake"></i><%= @user.birth_year %>年<%= @user.birth_month %>月<%= @user.birth_day %>日</div>
      <div class="text-center"><i class="fas fa-futbol"></i>好きなチーム：<%= @user.favorite_team %></div>
      <div class="text-center"><%= link_to "follow #{@user.followings.count}人", user_followings_path(@user), class: "text-dark", style: "font-size: 12px;" %> <%= link_to "followers #{@user.followers.count}人", user_followers_path(@user), class: "text-dark", style: "font-size: 12px;" %></div>
    </div>
  </div>
  <div class="offset-md-1 co-md-6 mt-2"><%= @user.profile %></div>
</div>
<div class="col-md-8">
  <%= render 'public/posts/index', posts: @user.posts %>
</div>