config/routes.rb
Rails.application.routes.draw do



  devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin,  skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

scope module: :public do
  root :to => "homes#top"
  resources :posts,  only: [:index, :new, :show, :edit, :update, :create, :destroy] do
    resources :post_comments, only: [:new, :create, :destroy]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  get '/post/hashtag/:name' => 'posts#hashtag'
  get '/post/hashtag' => 'posts#hashtag'

  get "users/quit" => "users#quit"
  patch "users/withdraw" => "users#withdraw"
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
    member do
      get :favorites
    end
    collection do
    get 'search'
    end
  end
  resources :chats, only: [:show, :create]
  resources :rooms, only: [:index]
  resources :notifications, only: [:index]
end

  namespace :admin do
    get "/" => "homes#top"
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <ul class="list-unstyled">
      <h5><%= model.errors.count %>件のエラー</h5>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_sidebar.html.erb
<table class="table table-borderless">
  <thead>
    <tr>
      <th class="text-left">
        <%= link_to posts_path, class: "btn" do %>
          <%= image_tag'logo.jpg', size: "120x100" %>
         <% end %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% if user_signed_in? %>
    <tr>
      <td class="text-left">
        <%= link_to notifications_path, style: "color: black;", class: "btn" do %>
            <i class="fas fa-bell"></i>
            <% if unchecked_notifications.any? %>
              <i class="fas fa-exclamation" style="color: red;"></i>
            <% end %>
            : 通知
        <% end %>
      </td>
    </tr>
    <tr>
      <td class="text-left"><%= link_to user_path(current_user), style: "color: black;", class: "btn" do %>
            <i class="fas fa-user-alt"></i>: my_page
          <% end %>

      </td>
    </tr>
    <tr>
      <td class="text-left">
        <%= link_to users_path, style: "color: black;", class: "btn" do %>
          <i class="fas fa-users"></i><i class="fas fa-search"></i>: users
        <% end %>
      </td>
    </tr>
    <tr>
      <td class="text-left">
        <%= link_to rooms_path, style: "color: black;", class: "btn" do %>
          <i class="fas fa-mail-bulk"></i>: DM
        <% end %>
      </td>
    </tr>
    <tr>
      <td class="text-left">
        <%= link_to favorites_user_path(current_user), style: "color: black;", class: "btn" do %>
          <i class="fas fa-thumbs-up"></i>: いいね
        <% end %>
      </td>
    </tr>
    <tr>
      <td class="text-left">
          <%= link_to destroy_user_session_path, method: :delete, style: "color: black;", class: "btn"  do %>
            <i class="fas fa-sign-out-alt"></i>:　Log out
          <% end %>
      </td>
    </tr>
    <% elsif admin_signed_in?%>
    <tr>
      <td><%= link_to "ユーザ一覧", admin_users_path, class: "btn" %></td>
    </tr>
    <tr>
      <td><%= link_to "投稿一覧", admin_posts_path, class: "btn" %></td>
    </tr>
    <tr>
      <td><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn" %></td>
    </tr>
    <% else %>
    <tr>
      <td class="text-left"><%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post, class: "btn" %></td>
    </tr>
    <tr>
      <td class="text-left"><%= link_to "新規登録", new_user_registration_path, class: "btn" %></td>
    </tr>
    <tr>
      <td class="text-left"> <%= link_to "ログイン", new_user_session_path, class: "btn" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_topbar.html.erb
<table class="table table-borderless mt-0">
  <tbody>
    <% if user_signed_in? %>
    <tr>
      <td class="text-center">
        <%= image_tag'logo.jpg', size: "80x80" %>
      </td>
      <td class="text-center">
        <%= link_to notifications_path, style: "color: black;" do %>
            <i class="fas fa-bell"></i>
            <% if unchecked_notifications.any? %>
              <i class="fas fa-exclamation" style="color: red;"></i>
            <% end %>
        <% end %>
      </td>
      <td class="text-center">
        <%= link_to new_post_path, style: "color: black;" do %>
          <i class="far fa-plus-square"></i>
        <% end %>
      </td>
      <td class="text-center">
        <%= link_to rooms_path, style: "color: black;" do %>
          <i class="fas fa-mail-bulk"></i>
        <% end %>
      </td>
      <td class="text-center">
        <%= link_to destroy_user_session_path, method: :delete, style: "color: black;"  do %>
            <i class="fas fa-sign-out-alt"></i>
        <% end %>
      </td>
    </tr>
    <% elsif admin_signed_in?%>
    <tr>
      <td class="text-center">
        <%= image_tag'logo.jpg', size: "80x80" %>
      </td>
    </tr>
    <% else %>
    <tr>
      <td class="text-center">
        <%= image_tag'logo.jpg', size: "80x80" %>
      </td>
      <td class="text-center"><%= link_to 'guest', users_guest_sign_in_path, method: :post, style: "font-size: 12px;" %></td>
      <td class="text-center"><%= link_to "新規登録", new_user_registration_path, style: "font-size: 12px;" %></td>
      <td class="text-center"> <%= link_to "ログイン", new_user_session_path, style: "font-size: 12px;" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_underbar.html.erb
<table class="table table-borderless col-12 mb-0" style="background-color: #66FFCC;">
  <tbody>
    <% if user_signed_in? %>
    <tr>
      <td class="text-center">
          <%= link_to user_path(current_user), style: "color: black;" do %>
            <i class="fas fa-user-alt"></i>
          <% end %>
      </td>
      <td class="text-center">
          <%= link_to posts_path, style: "color: black;" do %>
            <i class="fas fa-home"></i>
          <% end %>
      </td>
      <td class="text-center">
          <%= link_to users_path, style: "color: black;" do %>
            <i class="fas fa-users"></i><i class="fas fa-search"></i>
           <% end %>
      </td>
      <td class="text-center">
          <%= link_to favorites_user_path(current_user), style: "color: black;" do %>
            <i class="fas fa-thumbs-up"></i>
          <% end %>
      </td>
    </tr>
    <% elsif admin_signed_in?%>
    <tr>
      <td class="text-center">
        <%= link_to admin_users_path, style: "color: black;" do %>
          <i class="fas fa-users"></i>
        <% end %>
      </td>
    </tr>
    <tr>
      <td class="text-center">
        <%= link_to admin_posts_path, style: "color: black;" do %>
          <i class="fas fa-home-alt"></i>
        <% end %>
      </td>
    </tr>
    <tr>
      <td class="text-center">
        <%= link_to destroy_admin_session_path, method: :delete, style: "color: black;" do %>
          <i class="fas fa-sign-out"></i>
        <% end %>
      </td>
    </tr>
    <% else %>

    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Futfriend</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/livestamp/1.1.0/livestamp.js"></script>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container">
      <div class="row mt-3">
        <div class="col-12 d-block d-sm-none">
          <div class="sticky-top">
            <%= render "layouts/topbar" %>
          </div>
        </div>
        <div class="col-md-3 d-none d-sm-block">
          <div class="sticky-top offset-md-2" style="border-right: thick double #0000FF;">
            <%= render "layouts/sidebar" %>
          </div>
        </div>
        <div class="col-md-9 col-12">
          <%= flash[:error] %>
          <%= flash[:notice] %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
  <div class="col-12 d-block d-sm-none">
      <div class="sticky-bottom fixed-bottom">
        <%= render "layouts/underbar" %>
      </div>
  </div>
</html>